### ISSUE TITLE
Vagrant quickstart doesn't work

### ISSUE THREAD

**Issue by fblundun** [snowplow/snowplow.github.com#164]
The tail of the `vagrant up`'s output:

```
==> default: TASK: [github-pages | Install github pages in project folder] ***************** 
==> default: changed: [127.0.0.1]
==> default: 
==> default: PLAY RECAP ******************************************************************** 
==> default: 127.0.0.1                  : ok=22   changed=13   unreachable=0    failed=0   
==> default: Setting up Ansible to run out of checkout...
==> default: PATH=/vagrant/vagrant/ansible/bin:/usr/local/rvm/gems/ruby-2.0.0-p643/bin:/usr/local/rvm/gems/ruby-2.0.0-p643@global/bin:/usr/local/rvm/rubies/ruby-2.0.0-p643/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games:/usr/local/rvm/bin
==> default: PYTHONPATH=/vagrant/vagrant/ansible/lib:
==> default: ANSIBLE_LIBRARY=/vagrant/vagrant/ansible/library:/usr/share/ansible/
==> default: MANPATH=/vagrant/vagrant/ansible/docs/man:
==> default: Remember, you may wish to specify your host file with -i
==> default: Done!
==> default: ERROR: the playbook: /vagrant/vagrant/ does not appear to be a file
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.

```

**Comment by galvanic** [comment]
Once I've ssh'ed into the VM and follow the instructions, I get:

```
vagrant@vagrant-ubuntu-trusty-64:/vagrant$ bundle exec jekyll serve
The program 'bundle' is currently not installed. To run 'bundle' please ask your administrator to install the package 'bundler'
```

(Error which I didn't get yesterday)

So I install bundler:

```
vagrant@vagrant-ubuntu-trusty-64:/vagrant$ gem install bundler
Fetching: bundler-1.10.5.gem (100%)
Successfully installed bundler-1.10.5
1 gem installed
Installing ri documentation for bundler-1.10.5...
Installing RDoc documentation for bundler-1.10.5...
vagrant@vagrant-ubuntu-trusty-64:/vagrant$ bundle install
Fetching gem metadata from https://rubygems.org/..........
Fetching version metadata from https://rubygems.org/...
Fetching dependency metadata from https://rubygems.org/..
Installing RedCloth 4.2.9 with native extensions

Gem::Installer::ExtensionBuildError: ERROR: Failed to build gem native extension.

        /usr/bin/ruby1.9.1 extconf.rb
/usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require': cannot load such file -- mkmf (LoadError)
	from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
	from extconf.rb:1:in `<main>'


Gem files will remain installed in /tmp/bundler20150626-25355-h3imroRedCloth-4.2.9/gems/RedCloth-4.2.9 for inspection.
Results logged to /tmp/bundler20150626-25355-h3imroRedCloth-4.2.9/gems/RedCloth-4.2.9/ext/redcloth_scan/gem_make.out
An error occurred while installing RedCloth (4.2.9), and Bundler cannot continue.
Make sure that `gem install RedCloth -v '4.2.9'` succeeds before bundling.
vagrant@vagrant-ubuntu-trusty-64:/vagrant$ sudo gem install RedCloth -v '4.2.9'
Building native extensions.  This could take a while...
ERROR:  Error installing RedCloth:
	ERROR: Failed to build gem native extension.

        /usr/bin/ruby1.9.1 extconf.rb
/usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require': cannot load such file -- mkmf (LoadError)
	from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
	from extconf.rb:1:in `<main>'


Gem files will remain installed in /var/lib/gems/1.9.1/gems/RedCloth-4.2.9 for inspection.
Results logged to /var/lib/gems/1.9.1/gems/RedCloth-4.2.9/ext/redcloth_scan/gem_make.out
```

**Comment by jbeemster** [comment]
There is a disparity between the README and up.guidance for that command @galvanic. Guidance states just `jekyll serve` as opposed to `bundle exec jekyll serve`.  The former works fine for me so I presume there is no need for bundle exec at the front!

**Comment by bogaert** [comment]
This can be closed @fblundun?

**Comment by fblundun** [comment]
I just tried vagrant up and it worked... closing if nobody can reproduce the error.
